<p>Dit is de over mij pagina hier leer je wie ik ben en wat mijn intresses zijn.
</p>
<TABLE HEIGHT="250" WIDTH="850" BGCOLOR="white" BORDER="2" BORDERCOLOR="Black" CELLPADDING="5" CELLSPACING="0">
<FONT FACE="ARIAL">
<tr>
<TD>Naam</TD>
<TD>Wout Kuik</TD>
<TD>Artiest</TD>
<TD>ed sheeran</TD>
</TR>
<TR>
<FONT FACE="ARIAL">
<TD>Klas</TD>
<TD>4h1</TD>
<TD>Nummer</TD>
<TD>happier ed sheeran</TD>
</TR>
<TR>
<FONT FACE="ARIAL">
<TD>Wat weet ik al van Informatica</TD>
<TD>niet veel maar wil graag leren.</TD>
<TD>link</TD>
<TD> <A HREF="https://www.youtube.com/watch?v=iWZmdoY1aTE">"https://www.youtube.com/watch?v=iWZmdoY1aTE"</A></TD>
</TR>
<TR>
<FONT FACE="ARIAL">
<TD>Wat lijkt mij leuk om te leren</TD>
<TD>coderen zodat ik later een robot kan coderen.</TD>
<TD>Hobby´s</TD>
<TD>alles wat met slapen te maken heeft.</TD>
</TR>
<TR>
<FONT FACE="ARIAL">
<TD>Kleur</TD>
<TD>blauw</TD>
<TD>foto</TD>
<TD><A HREF="foto.html"><IMG BORDER="0" SRC="afbeelding/WhatsApp Image 2024-12-10 at 00.39.34.jpeg" WIDTH=50 HEIGHT=70></A></TD>
</TR>
   <TR>
<TR>
<FONT FACE="ARIAL">
<ul><TD><li>pretpark</li>
<li>atractie</li></TD>
<TD><li>disney</li>
    <br>
<li>barron</li></TD></ul>
</TR>
</TABLE>